version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing npm
      - npm install
  build:
    commands:
      npm run build
  post_build:
    commands:
      - echo Shopping List application deployed successfully!